# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.document.fr.core
canonical: https://interop.esante.gouv.fr/ig/document/core # the last part of canonical and id must be the same
name: FRDocumentCore # Should be an acronym
title: ANS IG document core
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 0.1.0-snapshot # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build # le release label doit être conforme au cycle de vie de la doctrine du ci-sis
jurisdiction: urn:iso:std:iso:3166#FR "France (la)"

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
  shownav: 'true'
  i18n-default-lang: fr
  i18n-lang:
    - en
  translation-sources:
    - input/translations/en
  path-expansion-params: '../../expansion-params.json'

dependencies:
  hl7.cda.uv.core: 2.0.3-sd
  ans.fr.terminologies: latest
  hl7.fhir.fr.core: 2.1.0
  hl7.fhir.uv.xver-r5.r4: latest
  ans.fhir.fr.annuaire: 1.1.0
  hl7.fhir.uv.fhir-clinical-document: latest
  ihe.pharm.mpd: 1.0.0-comment-2 

pages:
    index.md:
        title: Accueil
    structureGenerale.md:
        title: Structure générale document
        introduction.md:
            title: Introduction
        exigencesSpecifiques.md:
            title: Exigences spécifiques
        ressourcesCDA-struc-gen.md:
            title: CDA
        ressourcesFHIR-struc-gen.md:
            title: FHIR
    enteteDocument.md: 
        title: Entête document
        ressourcesCDA-entete.md:
            title: CDA
        ressourcesFHIR-entete.md:
            title: FHIR
    corpsDocument.md:
        title: Corps d'un document  
        ressourcesCDA-corps.md:
            title: CDA
        ressourcesFHIR-corps.md:
            title: FHIR
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    translationinfo.md:
        title: Informations sur la traduction

menu:
    Accueil: index.html
    Structure générale document:
        Introduction: introduction.html
        Exigences spécifiques: exigencesSpecifiques.html
        CDA: ressourcesCDA-struc-gen.html
        FHIR: ressourcesFHIR-struc-gen.html
        Mapping CDA / FHIR: mappingCDA-FHIR-struc-gen.html
    Entête document:
        Modèle logique métier: StructureDefinition-fr-lm-header-document.html
        CDA: ressourcesCDA-entete.html
        FHIR: ressourcesFHIR-entete.html
        Mapping Métier/CDA/FHIR: mappingCDA-FHIR-entete.html
    Corps d'un document:
        Modèle logique métier: StructureDefinition-fr-lm-corps-document.html
        CDA: ressourcesCDA-corps.html
        FHIR: ressourcesFHIR-corps.html
        Mapping Métier/CDA/FHIR: mappingCDA-FHIR-corps.html
    Ressources de conformité: artifacts.html


    
