Logical: FRLMCorpsDocument		
Id: fr-lm-corps-document					
Title: "Logical model - FR LM Corps document"				
Description: "Eléments métier du corps d'un document contenant les sections du document."	

* alerts 0..* FRLMAlerts "Section Points de vigilance"
* allergiesAndIntolerances 0..* FRLMAllergiesAndIntolerances  "Section Allergies et hypersensibilités"
* problems 0..* FRLMProblems "Section Problemès Actifs"
* medicationSummary 0..* FRLMMedicationSummary "Section Traitement"
* medicalDevicesAndImplants  0..* FRLMMedicalDevicesAndImplants "Section Dispositifs medicaux"
* procedures 0..* FRLMProcedures "Section Historique des actes"
* immunisations 0..* FRLMImmunisations "Section Vaccinations"
* functionalStatus 0..* FRLMFunctionalStatus "Section Statut fonctionnel"
* socialHistory 0..* FRLMSocialHistory "Section Habitus et modes de vie"
* pregnancyHistory 0..* FRLMSectionPregnancyHistory "Section Historique des grossesses"
* advanceDirectives 0..* FRLMAdvanceDirectives "Section Directives anticipées"
* observationResults 0..* FRLMObservationResults "Section Résultats"
* carePlans 0..* FRLMCarePlans "Section Plan de Soins"
* familyMedicalHistory  0..* FRLMFamilyMedicalHistory "Section Antécédents familiaux"
* historyOfPastIllness  0..* FRLMHistoryOfPastIllness "Section Antécédents médicaux"
* predictableAdverseDrugReactions 0..* FRLMPredictableAdverseDrugReaction "Section Effets indesirables"
* hazardousWorkingConditions 0..* FRLMHazardousWorkingConditions "Section Facteurs de risque professionnels non Codé"
* qrCode  0..* FRLMQRCode  "Section Codes à barres"
* note  0..* FRLMNote "Section Commentaire (Non-Codé)"
* medicationPrescriptions 0..* FRLMMedicationPrescription "Section Prescription médicaments"
* medicalDevicePrescriptions 0..* FRLMMedicalDevicePrescriptions "Section Prescription de dispositifs médicaux"
* presentedForm 0..* FRLMPresentedForm "Section Document PDF-copie"
* attachments 0..* FRLMAttachments "Section Documents ajoutés" 
* travelHistory 0..* FRLMSectionTravelHistory "Section Historique des voyages"
* patientStory 0..* FRLMPatientStory "Section Récit du patient"
* addendum 0..* FRLMAddendum "Section Addendum"
* vitalSigns 0..* FRLMVitalSigns "Section Signes vitaux"
* resultData 0..* FRLMResultData "section Compte rendu de biologie de 1er niveau"
* examinationReport 0..* FRLMExaminationReport "Section Acte d'imagerie"
* orderInformation 0..* FRLMOrderInformation "Section Demande d'examen"
* comparisonStudy 0..* FRLMComparisonStudy "Section Examen comparatif"
* exposureInformation 0..* FRLMExposureInformation "Section Exposition aux radiations"
* supportingInformation 0..* FRLMSupportingInformation "Section Informations cliniques"
* dicomStudyMetadata 0..* FRLMDicomStudyMetadata "Section object catalog"
* recommendation 0..* FRLMRecommendation "Section Recommandation"
* conclusion 0..* FRLMConclusion "Section Conclusion"
* medicationDispensations 0..* FRLMMedicationDispensations "Section Dispensation médicaments"
* patientEducation 0..* FRLMPatientEducation "Section Education du patient"
* patientHistory  0..* FRLMPatientHistory "Section Historique du patient"
* reasonForReferral 0..* FRLMReasonForReferral "Section Raison de la recommandation"
* courseOfEncounter 0..* FRLMCourseOfEncounter "Section Résultats d'événements"
* hospitalDischargeMedications 0..* FRLMHospitalDischargeMedications "Section Traitement à la sortie"
* traitementsAdministres 0..* FRLMTraitementsAdministres "Section Traitements administrés"